### ISSUE TITLE
Broken links generated

### ISSUE THREAD

**Issue by pyjarrett** [ada-lang-io/import-style-guide#2]
Ran into some problems with some of the links generated by the wikibooks.  I manually removed them to get the style guide to work on ada-lang.io, but the generator will need to have these fixed somehow.

```
Exhaustive list of all broken links found:

- On source page path = /docs/style-guide/Ada_Style_Guide:
   -> linking to Ada_Programming/Ada_2012 (resolved as: /docs/style-guide/Ada_Programming/Ada_2012)
   -> linking to Ada_Programming (resolved as: /docs/style-guide/Ada_Programming)
   -> linking to Ada_Programming/Ada_95 (resolved as: /docs/style-guide/Ada_Programming/Ada_95)
   -> linking to Ada_Programming/Ada_83 (resolved as: /docs/style-guide/Ada_Programming/Ada_83)
   -> linking to Main_Page (resolved as: /docs/style-guide/Main_Page)
```

**Comment by mgrojo** [comment]
Another option is also importing the "Ada Programming" Wikibook.

I'm one of the Wikibook's author and I think it would be nice to have a copy in ada-lang.io, provided that edit links, as with #3, and a note about licensing, as currently implemented, are inserted in every page.

I guess the programming book will be more difficult to import, due to size and heavy template usage.
